openapi: "3.0.0"
info:
  title: "Customer Management API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8097/CustomerManagement"
paths:
  /add:
    post:
      summary: "Add Customer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: "Customer added."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    CustomerResponse:
      type: object
      properties:
        customerId:
          type: string
