openapi: "3.0.0"
info:
  title: "Document Verification API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8097/DocumentVerify"
paths:
  /verify:
    post:
      summary: "Verify Document"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: "Document verified."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationStatus'
components:
  schemas:
    Document:
      type: object
      properties:
        docType:
          type: string
        docNumber:
          type: string
    VerificationStatus:
      type: object
      properties:
        status:
          type: string

