openapi: "3.0.0"
info:
  title: "Inventory API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8097/Inventory"
paths:
  /list:
    get:
      summary: "List Inventory"
      responses:
        '200':
          description: "Inventory listed."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryList'
components:
  schemas:
    InventoryList:
      type: array
      items:
        type: object
        properties:
          itemId:
            type: string
          quantity:
            type: integer