openapi: "3.0.0"
info:
  title: "Notification API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8097/Notification"
paths:
  /send:
    post:
      summary: "Send Notification"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRequest'
      responses:
        '200':
          description: "Notification sent successfully."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
  /history:
    get:
      summary: "Notification History"
      responses:
        '200':
          description: "Notification history retrieved."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationHistory'
components:
  schemas:
    NotificationRequest:
      type: object
      properties:
        to:
          type: string
        message:
          type: string
    NotificationResponse:
      type: object
      properties:
        messageId:
          type: string
    NotificationHistory:
      type: array
      items:
        $ref: '#/components/schemas/NotificationResponse'
