openapi: 3.0.0
info:
  title: Branch and ATM Locator API
  version: 1.0.0
  description: API to find branch locations and ATMs
servers:
  - url: http://localhost:8101/BranchLocator
    description: Production server

paths:
  /locations:
    get:
      summary: Get all branch and ATM locations
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'

components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
        type:
          type: string
