version: '3'
services:
  proxy:
    image: caddy
    container_name: caddy_computing
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '8099:80'
    networks:
      - computing
    depends_on:
      - 3DModelingAndAnimation
      - AIEnhancedGraphics
      - AIVideoAnalytics
      - AutonomousVehicle
      - CloudGaming
      - HighPerformanceComputing
      - NaturalLanguageProcessing
      - RealTimeRayTracing
      - RoboticsControlAndSimulation
      - VirtualRealityRendering
  3DModelingAndAnimation:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/3DModelingAndAnimation.yaml
    networks:
      - computing
  AIEnhancedGraphics:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/AIEnhancedGraphics.yaml
    networks:
      - computing
  AIVideoAnalytics:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/AIVideoAnalytics.yaml
    networks:
      - computing
  AutonomousVehicle:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/AutonomousVehicle.yaml
    networks:
      - computing
  CloudGaming:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/CloudGaming.yaml
    networks:
      - computing
  HighPerformanceComputing:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/HighPerformanceComputing.yaml
    networks:
      - computing
  NaturalLanguageProcessing:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/NaturalLanguageProcessing.yaml
    networks:
      - computing
  RealTimeRayTracing:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/RealTimeRayTracing.yaml
    networks:
      - computing
  RoboticsControlAndSimulation:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/RoboticsControlAndSimulation.yaml
    networks:
      - computing
  VirtualRealityRendering:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwaycomputing/apis/VirtualRealityRendering.yaml
    networks:
      - computing 
networks:
  computing: