openapi: "3.0.0"
info:
  title: "Compliance API"
  version: "1.0.0"
servers:
  - url: "https://compliance.sample-server.com"
paths:
  /check:
    get:
      summary: "Check Compliance"
      responses:
        '200':
          description: "Compliance status retrieved."