openapi: "3.0.0"
info:
  title: "Loan Origination API"
  version: "1.0.0"
servers:
  - url: "https://loan-origination.sample-server.com"
paths:
  /initiate:
    post:
      summary: "Initiate Loan"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanRequest'
      responses:
        '200':
          description: "Loan initiated successfully."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanResponse'
  /status:
    get:
      summary: "Check Loan Status"
      responses:
        '200':
          description: "Loan status retrieved."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanStatus'
components:
  schemas:
    LoanRequest:
      type: object
      properties:
        amount:
          type: number
        term:
          type: integer
    LoanResponse:
      type: object
      properties:
        loanId:
          type: string
    LoanStatus:
      type: object
      properties:
        loanId:
          type: string
        status:
          type: string
