openapi: "3.0.0"
info:
  title: "Payment Gateway API"
  version: "1.0.0"
servers:
  - url: "https://payment-gateway.sample-server.com"
paths:
  /process:
    post:
      summary: "Process Payment"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: "Payment processed."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
components:
  schemas:
    PaymentRequest:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
    PaymentResponse:
      type: object
      properties:
        transactionId:
          type: string
        status:
          type: string

