openapi: "3.0.0"
info:
  title: "Payment Gateway API"
  version: "1.0.0"
servers:
  - url: "https://payment-gateway.sample-server.com"
paths:
  /process:
    post:
      summary: "Process Payment"
      responses:
        '200':
          description: "Payment processed."
