
openapi: 3.0.0
info:
  title: AI-Enhanced Graphics API
  version: 1.0.0
  description: API for improving graphics rendering using artificial intelligence.
servers:
  - url: http://localhost:8099/AIEnhancedGraphics
    description: Production server
paths:
  /enhance:
    post:
      summary: Enhance an image using AI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageData'
      responses:
        '200':
          description: Successfully enhanced image
          content:
            image/png:
              schema:
                type: string
                format: binary
components:
  schemas:
    ImageData:
      type: object
      properties:
        image:
          type: string
          format: binary
          description: Base64 encoded image data.
        settings:
          $ref: '#/components/schemas/EnhancementSettings'
      example:
        image: "base64EncodedImageData=="
        settings:
          detailEnhancement: true
          colorCorrection: true
    EnhancementSettings:
      type: object
      properties:
        detailEnhancement:
          type: boolean
          description: "Enable or disable detail enhancement."
        colorCorrection:
          type: boolean
          description: "Enable or disable color correction."
