
openapi: 3.0.0
info:
  title: AI Video Analytics API
  version: 1.0.0
  description: API for real-time video stream analysis using artificial intelligence.
paths:
  /analyze:
    post:
      summary: Analyze a video stream
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoStream'
      responses:
        '200':
          description: Successfully analyzed video stream
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResult'

components:
  schemas:
    VideoStream:
      type: object
      properties:
        url:
          type: string
          format: uri
          description: URL of the video stream.
      example:
        url: "http://example.com/video_stream"

    AnalysisResult:
      type: object
      properties:
        objectsDetected:
          type: array
          items:
            $ref: '#/components/schemas/DetectedObject'
        timestamp:
          type: string
          format: date-time

    DetectedObject:
      type: object
      properties:
        type:
          type: string
          description: "Type of the detected object."
        position:
          $ref: '#/components/schemas/Position'
        confidence:
          type: number
          format: float
          description: "Confidence score of the detection."

    Position:
      type: object
      properties:
        x:
          type: integer
          description: "X-coordinate on the video frame."
        y:
          type: integer
          description: "Y-coordinate on the video frame."
