
openapi: 3.0.0
info:
  title: Natural Language Processing API
  version: 1.0.0
  description: API for language understanding, translation, and text generation using NLP techniques.
paths:
  /translate:
    post:
      summary: Translate text from one language to another
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslationRequest'
      responses:
        '200':
          description: Successfully translated text
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslationResponse'

  /generate:
    post:
      summary: Generate text based on a prompt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextGenerationRequest'
      responses:
        '200':
          description: Successfully generated text
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextGenerationResponse'

components:
  schemas:
    TranslationRequest:
      type: object
      properties:
        sourceLanguage:
          type: string
          description: "ISO code of the source language."
        targetLanguage:
          type: string
          description: "ISO code of the target language."
        text:
          type: string
          description: "Text to be translated."
      example:
        sourceLanguage: "en"
        targetLanguage: "es"
        text: "Hello, world!"

    TranslationResponse:
      type: object
      properties:
        translatedText:
          type: string
          description: "Translated text."

    TextGenerationRequest:
      type: object
      properties:
        prompt:
          type: string
          description: "Text prompt for generation."
        maxLength:
          type: integer
          description: "Maximum length of the generated text."
      example:
        prompt: "Write a short story about a robot."
        maxLength: 500

    TextGenerationResponse:
      type: object
      properties:
        generatedText:
          type: string
          description: "Generated text based on the prompt."
