openapi: 3.0.0
x-stoplight:
  id: p7gyxfh4h5sfi
info:
  title: Accounts
  version: '1.0'
  description: Manage account at Griffin Bank
servers:
  - url: 'http://localhost:3000'
paths:
  '/listAccount/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/account'
      operationId: get-account-id
      description: Get account by accountId
  '/listAccounts/{customerId}':
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/accounts'
      operationId: get-account-customerId
      description: Get all accounts for customer by customerId
components:
  schemas:
    account:
      title: account
      x-stoplight:
        id: amcrlf2grl7ub
      type: object
      properties:
        id:
          type: string
          x-faker: datatype.uuid
        customerId:
          type: string
          x-faker: finance.account
        accountType:
          type: string
          enum:
            - checking
            - savings
            - investment
        accountBalance:
          x-faker:
            datatype.number:
              min: 100
              max: 999999
              precision: 0.01
          type: number
    accounts:
      title: accounts
      x-stoplight:
        id: rg74ao67aahxt
      type: string
      x-faker: datatype.uuid
  responses:
    account:
      description: Single account
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/account'
    accounts:
      description: List of accounts
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/accounts'
x-extension-1: null
