openapi: 3.0.0
x-stoplight:
  id: ebmhs0sqwnpn0
info:
  title: Balance Inquiry
  version: '1.0'
  description: Returns Information Reporting account balance data.
servers:
  - url: 'http://localhost:8095/balance-inquiries'
paths:
  /current-day:
    parameters: []
    post:
      summary: ''
      operationId: post-current-day
      responses:
        '200':
          $ref: '#/components/responses/200-current-day'
      requestBody:
        $ref: '#/components/requestBodies/balanceInquiry'
  /previous-day:
    post:
      summary: ''
      operationId: post-balance-inqury-previous-day
      responses:
        '200':
          $ref: '#/components/responses/200-previous-day'
        '':
          $ref: '#/components/responses/200-previous-day'
      requestBody:
        $ref: '#/components/requestBodies/balanceInquiryDateRange'
      description: Returns previous day Reporting account balance data for the prior business day back to the full two year client retention.
    parameters: []
components:
  schemas:
    balanceInquirySingleDate:
      type: object
      properties:
        accounts:
          type: array
          items:
            type: object
            properties:
              accountNumber:
                type: string
              bankId:
                type: string
        balanceAsOfDate:
          type: string
      x-examples:
        Example 1:
          accounts:
            - accountNumber: '601022222222'
              bankId: BOFAFRPP
          balanceAsOfDate: '2017-07-04'
    balanceResponse:
      type: object
      properties:
        accountBalances:
          type: object
          properties:
            accountNumber:
              type: string
            balances:
              type: array
              items:
                type: object
                properties:
                  amount:
                    type: string
                  lastUpdatedDate:
                    type: string
                  transactionCode:
                    type: string
                  transactionDescription:
                    type: string
            bankId:
              type: string
            currency:
              type: string
      x-examples:
        Example 1:
          accountBalances:
            accountNumber: '600811111111'
            balances:
              - amount: '983.97'
                lastUpdatedDate: '2017-07-04'
                transactionCode: '010'
                transactionDescription: Opening Ledger Balance
            bankId: BOFAGB22
            currency: EUR
    balanceInquiryDateRange:
      type: object
      properties:
        accounts:
          type: array
          items:
            type: object
            properties:
              accountNumber:
                type: string
              bankId:
                type: string
        fromDate:
          type: string
        toDate:
          type: string
      x-examples:
        Example 1:
          accounts:
            - accountNumber: '601022222222'
              bankId: BOFAFRPP
          fromDate: '2017-11-21'
          toDate: '2017-11-21'
    balanceResponsePreviousDay:
      type: object
      properties:
        accountTransactions:
          type: object
          properties:
            accountNumber:
              type: string
            bankId:
              type: string
            currency:
              type: string
            transactions:
              type: array
              items:
                type: object
                properties:
                  amount:
                    type: string
                  asOfDate:
                    type: string
                  availability1DayAmount:
                    type: string
                  availability2PlusDayAmount:
                    type: string
                  availabilityImmediateAmount:
                    type: string
                  bankReference:
                    type: string
                  creditDebitIndicator:
                    type: string
                  customerReference:
                    type: string
                  detailText:
                    type: string
                  itemCount:
                    type: string
                  transactionCode:
                    type: string
                  transactionDescription:
                    type: string
                  transactionType:
                    type: string
                  valueDate:
                    type: string
      x-examples:
        Example 1:
          accountTransactions:
            accountNumber: '601022222222'
            bankId: BOFAFRPP
            currency: EUR
            transactions:
              - amount: '1.00'
                asOfDate: '2017-11-21'
                availability1DayAmount: string
                availability2PlusDayAmount: string
                availabilityImmediateAmount: string
                bankReference: '555555555555'
                creditDebitIndicator: Debit
                customerReference: CUSTREF123
                detailText: BENEFICIARY UNSTRUCTURED DETAIL TEXT
                itemCount: '1'
                transactionCode: '400'
                transactionDescription: Total Debits
                transactionType: Summary
                valueDate: '2017-11-21'
  requestBodies:
    balanceInquiry:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/balanceInquirySingleDate'
          examples: {}
      description: Balance Inquiry Request
    balanceInquiryDateRange:
      content:
        application/json:
          schema:
            type: object
  responses:
    200-current-day:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/balanceResponse'
    200-previous-day:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/balanceResponsePreviousDay'
tags:
  - name: Account Information
