openapi: 3.0.0
x-stoplight:
  id: iyg5or36vs0ri
info:
  title: Portfolios
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:8095/portfolioManagement/v1'
paths:
  '/listPortfolios/{customerId}':
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/portfolios'
      operationId: get-listPortfolios-customerId
  '/listPortfolio/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/portfolio'
      operationId: get-listPortfolio-id
components:
  schemas:
    portfolio:
      title: portfolio
      x-stoplight:
        id: pd9q7wvjr2rrw
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        accountType:
          type: string
        accountBalance:
          type: string
    portfolios:
      title: portfolios
      x-stoplight:
        id: jx9c3eo5f9opy
      type: array
      items:
        type: string
  responses:
    portfolio:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/portfolio'
    portfolios:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/portfolios'
