openapi: 3.0.0
x-stoplight:
  id: iyg5or36vs0ri
info:
  title: Portfolios
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/listPortfolios/{customerId}':
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/portfolios'
      operationId: get-listPortfolios-customerId
  '/listPortfolio/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/portfolio'
      operationId: get-listPortfolio-id
components:
  schemas:
    portfolio:
      title: Portfolio
      x-stoplight:
        id: tvc2h0gytxkhd
      type: object
      properties:
        id:
          type: string
    portfolios:
      title: Portfolios
      x-stoplight:
        id: fp8aap4r8w4l5
      type: object
      properties:
        id:
          type: array
          items:
            type: string
  responses:
    portfolio:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/portfolio'
    portfolios:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/portfolios'
