version: '3'
services:
  proxy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '8096:80'
    depends_on:
      - AppointmentScheduling
      - ElectronicHealthcareRecords
      - InsuranceAndBilling
      - HealthAndFitnessData
      - PharmacyAndMedication
      - Telemedicine
  AppointmentScheduling:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwayhealth/apis/AppointmentScheduling.yaml
  ElectronicHealthcareRecords:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwayhealth/apis/ElectronicHealthcareRecords.yaml
  InsuranceAndBilling:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwayhealth/apis/InsuranceaAndBilling.yaml
  HealthAndFitnessData:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwayhealth/apis/HealthAndFitnessData.yaml
  PharmacyAndMedication:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwayhealth/apis/PharmacyAndBilling.yaml
  Telemedicine:
    image: stoplight/prism:4
    command: >
      mock -d -p 3000 --host 0.0.0.0
      https://raw.githubusercontent.com/axway-apim/mavericks/master/demo/axwayhealth/apis/Telemedecine.yaml

