openapi: 3.0.0
info:
  title: Logistics Order Management API
  description: API for managing logistics orders.
  version: 1.0.0

servers:
  - url: http://localhost:8098/OrderManagement
    description: Production server

components:
  schemas:
    ShippingOrder:
      type: object
      properties:
        orderId:
          type: string
          description: Unique identifier for the shipping order.
        senderName:
          type: string
          description: Name of the sender.
        recipientName:
          type: string
          description: Name of the recipient.
        destinationAddress:
          type: string
          description: Destination address of the shipment.
        weight:
          type: number
          format: float
          description: Weight of the package in kilograms.
        shippingMethod:
          type: string
          enum: [Ocean, Air, Ground, Rail, Intermodal]
        shippingStatus:
          type: string
          enum: [Pending, Shipped, Delivered]
          description: Current status of the shipping order.
        lastReportedLocation:
          type: string
          description: Last reported location of shipment.
        lastLocationUpdate:
          type: string
          x-faker: date.past
          format: "date-time"
          dscription: Date and Time of last location update.

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  orderManagement/shippingOrders:
    post:
      summary: Create Shipping Order
      description: Create a new shipping order.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShippingOrder'
      responses:
        '201':
          description: Shipping order created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShippingOrder'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '500':
          description: Internal Server Error.

  orderManagement/shippingOrders/{orderId}:
    parameters:
      - name: orderId
        in: path
        required: true
        description: The ID of the shipping order to retrieve.
        schema:
          type: string

    put:
      summary: Update Shipping Order
      description: Update information about a specific shipping order.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShippingOrder'
      responses:
        '200':
          description: Shipping order updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShippingOrder'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '404':
          description: Shipping order not found.
        '500':
          description: Internal Server Error.

    delete:
      summary: Cancel Shipping Order
      description: Cancel a specific shipping order.
      responses:
        '204':
          description: Shipping order canceled successfully.
        '401':
          description: Unauthorized.
        '404':
          description: Shipping order not found.
        '500':
          description: Internal Server Error.
