openapi: 3.0.0
info:
  title: Logistics Shipping, Track, and Trace API
  description: API for managing logistics, shipping, and package tracking.
  version: 1.0.0

servers:
  - url: http://localhost:8098/TrackAndTrace
    description: Production server

components:
  schemas:
    ShippingOrder:
      type: object
      properties:
        orderId:
          type: string
          description: Unique identifier for the shipping order.
        senderName:
          type: string
          x-faker: person.fullName
          description: Name of the sender.
        recipientName:
          type: string
          x-faker:
            person.fullName:
              firstName: string
              lastName: string
          description: Name of the recipient.
        destinationAddress:
          type: string
          x-faker:
            location.streetAddress
          description: Destination address of the shipment.
        weight:
          type: number
          x-faker:
            datatype.number:
              min: 1
              max: 200
          format: string
          description: Weight of the package in kilograms.
        shippingMethod:
          type: string
          enum: [Ocean, Air, Ground, Rail, Intermodal]
        shippingStatus:
          type: string
          enum: [Pending, Shipped, Delivered]
          description: Current status of the shipping order.
        lastReportedLocation:
          type: string
          x-faker:
            location.streetAddress
          description: Last reported location of shipment.
        lastLocationUpdate:
          type: string
          x-faker: date.past
          format: "date-time"
          dscription: Date and Time of last location update.

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /shipping-orders:
    get:
      summary: List Shipping Orders
      description: Retrieve a list of shipping orders.
      responses:
        '200':
          description: A list of shipping orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShippingOrder'
        '401':
          description: Unauthorized.
        '500':
          description: Internal Server Error.

  /shipping-orders/{orderId}:
    parameters:
      - name: orderId
        in: path
        required: true
        description: The ID of the shipping order to retrieve.
        schema:
          type: string

    get:
      summary: Get Shipping Order
      description: Retrieve detailed information about a specific shipping order.
      responses:
        '200':
          description: Shipping order information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShippingOrder'
        '401':
          description: Unauthorized.
        '404':
          description: Shipping order not found.
        '500':
          description: Internal Server Error.
