openapi: 3.0.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: "http://localhost:8100/Reservations"
paths:
  /reservations:
    post:
      summary: Create Reservation
      requestBody:
        description: Reservation details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Customer's name
                date:
                  type: string
                  format: date
                  description: Reservation date (YYYY-MM-DD)
                time:
                  type: string
                  format: time
                  description: Reservation time (HH:MM)
      responses:
        '201':
          description: Reservation created successfully

    put:
      summary: Modify Reservation
      parameters:
        - name: reservationId
          in: path
          required: true
          description: ID of the reservation to modify
          schema:
            type: integer
      requestBody:
        description: Updated reservation details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Customer's name
                date:
                  type: string
                  format: date
                  description: Reservation date (YYYY-MM-DD)
                time:
                  type: string
                  format: time
                  description: Reservation time (HH:MM)
      responses:
        '200':
          description: Reservation modified successfully
