openapi: 3.0.0
info:
  title: Restaurant Information API
  version: 1.0.0
servers:
  - url: "http://localhost:8100/RestaurantInfo"
paths:
  /location:
    get:
      summary: Get Restaurant Location
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  latitude:
                    type: number
                  longitude:
                    type: number

  /restaurant-info:
    get:
      summary: Get Restaurant Information
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  address:
                    type: string
                  contact:
                    type: string
                  cuisine:
                    type: string
