openapi: 3.1.0
info:
  title: Health and Fitness Data API
  summary: Manage patient health and fitness data
  description: API for managing health and fitness data.
  version: 1.0.0

servers:
  - url: http://localhost:8096/HealthAndFitness
    description: Production server

components:
  schemas:
    HealthRecord:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique health record ID.
        userId:
          type: integer
          description: ID of the user to whom the health record belongs.
        date:
          type: string
          format: date
          description: Date of the health record entry (YYYY-MM-DD).
        weight:
          type: number
          format: float
          description: Weight of the user (in kilograms).
        height:
          type: number
          format: float
          description: Height of the user (in centimeters).
        heartRate:
          type: integer
          description: Heart rate (beats per minute).
        steps:
          type: integer
          description: Number of steps taken.
        caloriesBurned:
          type: integer
          description: Calories burned (kcal).
    
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /health-records:
    get:
      summary: List Health Records
      description: Retrieve a list of health records for a user.
      parameters:
        - name: userId
          in: query
          required: true
          description: ID of the user whose health records are to be retrieved.
          schema:
            type: integer
      responses:
        '200':
          description: A list of health records.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthRecord'
        '401':
          description: Unauthorized.
        '500':
          description: Internal Server Error.

    post:
      summary: Create a Health Record
      description: Create a new health record entry for a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthRecord'
      responses:
        '201':
          description: Health record created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthRecord'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '500':
          description: Internal Server Error.

  /health-records/{healthRecordId}:
    parameters:
      - name: healthRecordId
        in: path
        required: true
        description: The ID of the health record entry to retrieve or update.
        schema:
          type: integer
          format: int64

    get:
      summary: Get a Health Record
      description: Retrieve information about a specific health record entry.
      responses:
        '200':
          description: Health record information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthRecord'
        '401':
          description: Unauthorized.
        '404':
          description: Health record not found.
        '500':
          description: Internal Server Error.

    put:
      summary: Update a Health Record
      description: Update information about a specific health record entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthRecord'
      responses:
        '200':
          description: Health record updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthRecord'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '404':
          description: Health record not found.
        '500':
          description: Internal Server Error.

    delete:
      summary: Delete a Health Record
      description: Delete a specific health record entry.
      responses:
        '204':
          description: Health record deleted successfully.
        '401':
          description: Unauthorized.
        '404':
          description: Health record not found.
        '500':
          description: Internal Server Error.
