openapi: 3.0.0
info:
  title: Telemedicine and Video Consultation API
  description: API for managing telemedicine appointments and video consultations.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

components:
  schemas:
    Consultation:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique consultation ID.
        date:
          type: string
          format: date-time
          description: Date and time of the consultation (ISO 8601 format).
        patientId:
          type: integer
          description: ID of the patient participating in the consultation.
        doctorId:
          type: integer
          description: ID of the doctor or healthcare provider conducting the consultation.
        meetingLink:
          type: string
          format: uri
          description: URL or meeting link for the video consultation.
        status:
          type: string
          enum: [Scheduled, InProgress, Completed, Canceled]
          description: Status of the consultation.

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /consultations:
    get:
      summary: List Consultations
      description: Retrieve a list of all consultations.
      responses:
        '200':
          description: A list of consultations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consultation'
        '401':
          description: Unauthorized.
        '500':
          description: Internal Server Error.

    post:
      summary: Schedule a Consultation
      description: Schedule a new video consultation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consultation'
      responses:
        '201':
          description: Consultation scheduled successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consultation'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '500':
          description: Internal Server Error.

  /consultations/{consultationId}:
    parameters:
      - name: consultationId
        in: path
        required: true
        description: The ID of the consultation to retrieve or update.
        schema:
          type: integer
          format: int64

    get:
      summary: Get a Consultation
      description: Retrieve information about a specific consultation.
      responses:
        '200':
          description: Consultation information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consultation'
        '401':
          description: Unauthorized.
        '404':
          description: Consultation not found.
        '500':
          description: Internal Server Error.

    put:
      summary: Update a Consultation
      description: Update information about a specific consultation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consultation'
      responses:
        '200':
          description: Consultation updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consultation'
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '404':
          description: Consultation not found.
        '500':
          description: Internal Server Error.

    delete:
      summary: Cancel a Consultation
      description: Cancel a specific consultation.
      responses:
        '204':
          description: Consultation canceled successfully.
        '401':
          description: Unauthorized.
        '404':
          description: Consultation not found.
        '500':
          description: Internal Server Error.
