openapi: 3.1.0
info:
  title: Medical Urgent Care Locator API
  summary: Locate urgent care facilities and facility information
  description: API for locating medical urgent care facilities and obtaining facility information.
  version: 1.0.0

servers:
  - url: http://localhost:8096/UrgetnCareLocator
    description: Production server

components:
  schemas:
    UrgentCareFacility:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique urgent care facility ID.
        name:
          type: string
          description: Name of the urgent care facility.
        address:
          type: string
          description: Street address of the facility.
        city:
          type: string
          description: City where the facility is located.
        state:
          type: string
          description: State or province where the facility is located.
        zipCode:
          type: string
          description: ZIP or postal code of the facility.
        phoneNumber:
          type: string
          description: Phone number of the facility.

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /urgent-care-facilities:
    get:
      summary: List Urgent Care Facilities
      description: Retrieve a list of medical urgent care facilities within a specified area.
      parameters:
        - name: city
          in: query
          description: City name to filter urgent care facilities.
          schema:
            type: string
        - name: state
          in: query
          description: State or province name to filter urgent care facilities.
          schema:
            type: string
        - name: zipCode
          in: query
          description: ZIP or postal code to filter urgent care facilities.
          schema:
            type: string
      responses:
        '200':
          description: A list of urgent care facilities.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UrgentCareFacility'
        '401':
          description: Unauthorized.
        '500':
          description: Internal Server Error.

  /urgent-care-facilities/{facilityId}:
    parameters:
      - name: facilityId
        in: path
        required: true
        description: The ID of the urgent care facility to retrieve.
        schema:
          type: integer
          format: int64

    get:
      summary: Get Urgent Care Facility Details
      description: Retrieve detailed information about a specific urgent care facility.
      responses:
        '200':
          description: Urgent care facility information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrgentCareFacility'
        '401':
          description: Unauthorized.
        '404':
          description: Urgent care facility not found.
        '500':
          description: Internal Server Error.
